FROM  nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04
MAINTAINER liulianjushi@126.com
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG C.UTF-8
ENV TZ Asia/Shanghai
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
WORKDIR /root/
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list; \
    apt-get update; \
    apt-get install -y --no-install-recommends tzdata wget python3 python3-distutils python3-pip libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev; \
    python3 -m pip --no-cache-dir --timeout 3000 install --upgrade "pip<21.4" setuptools ;\
    pip3 config set global.index-url https://mirrors.cloud.tencent.com/pypi/simple; \
    pip3 --no-cache-dir --timeout 3000 install jupyterlab==3.2.9  opencv-python; \
    jupyter labextension install @telamonian/theme-darcula; \
    jupyter lab --generate-config; \
    echo "c.NotebookApp.allow_root = True\nc.NotebookApp.ip = '0.0.0.0'\nc.NotebookApp.open_browser = False\nc.NotebookApp.password = u'sha1:84517c5a4458:388c4168ca76582b91759c84fdf66d679decc2c0'\nc.NotebookApp.terminado_settings = {'shell_command' : ['/bin/bash']}\nc.NotebookApp.notebook_dir = u'/root/workspace/'" >> /root/.jupyter/jupyter_notebook_config.py; \
    mkdir /root/workspace/; \
    apt-get autoremove && apt-get autoclean ;\
    rm -rf /var/lib/apt/lists/*
CMD jupyter lab --ip="0.0.0.0" --allow-root
