FROM zhaoliu09/jupyter:ubuntu18.04
MAINTAINER liulianjushi@126.com
ENV LANG C.UTF-8
RUN apt-get update;\
    apt-get install -y --no-install-recommends libglib2.0-0 libsm6 libxrender1 libxtst6 libgomp1; \
    pip3 --no-cache-dir install --upgrade pip tensorflow-gpu opencv-python keras -i https://pypi.tuna.tsinghua.edu.cn/simple ;\
    apt-get autoremove && apt-get autoclean ;\
    rm -rf /var/lib/apt/lists/*
CMD jupyter lab --ip="0.0.0.0" --allow-root
